import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import { SessionProvider } from 'next-auth/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1.0,
  // maximumScale: 1,
  // userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${inter.className} w-full flex justify-center h-full min-h-screen bg-gray-400`}
      >
        <SessionProvider>
          <div className="overflow-hidden flex flex-col relative w-full min-h-screen h-full max-w-[475px] bg-white">
            {children}
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
